### create mandalart
POST http://0.0.0.0:8080/mandalarts
Content-Type: application/json

{
  "title": "mandalart title",
  "goal": "mandalart goal"
}

### get mandalart detail
GET http://0.0.0.0:8080/mandalarts/1

### create main goal
POST http://0.0.0.0:8080/mandalarts/1/main-goals
Content-Type: application/json

{
  "row": 4,
  "col": 4,
  "goal": "goal"
}

### create sub goal
POST http://0.0.0.0:8080/mandalarts/1/main-goals/1/sub-goals

