### create mandalart
POST http://0.0.0.0:8080/mandalarts
Content-Type: application/json

{
  "title": "mandalart title",
  "goal": "mandalart goal"
}

### get mandalart detail
GET http://0.0.0.0:8080/mandalarts/1

### update mandalart
PATCH http://0.0.0.0:8080/mandalarts/1
Content-Type: application/json

{
  "title": "updated title"
}

### delete mandalart
DELETE http://0.0.0.0:8080/mandalarts/1

### create main goal
POST http://0.0.0.0:8080/mandalarts/1/main-goals
Content-Type: application/json

{
  "location": 1,
  "goal": "goal"
}

### get main goal
GET http://0.0.0.0:8080/mandalarts/1/main-goals/0

### create sub goal
POST http://0.0.0.0:8080/mandalarts/1/main-goals/1/sub-goals
Content-Type: application/json

{
  "location": 1,
  "goal": "goal"
}

### create sub goal action
POST http://0.0.0.0:8080/mandalarts/1/main-goals/1/sub-goals/1/sub-goal-actions
Content-Type: application/json

{
  "action": "Do Right Now"
}

